### ISSUE TITLE
Explanation required

### ISSUE THREAD

**Issue by dotsquid** [litefeel/PrefabRefByInsideSO#1]
Hi there!
Can you please explain what are the benefits of embedding the SO into the prefab? I can't figure out the use case of this trick.
Thanks in advance.

**Comment by litefeel** [comment]
Hi.
Consider such a situation.
1. The prefab with data will be clone many times.
2. But this prefab instance has same data.
3. So the data should save to SO.
4. So the data and prefab are a whole
5. It will be more reasonable to save the prefab and data to the same file.

**Comment by dotsquid** [comment]
Hi. Thanks for reply.
If the instances of the prefab should have the same data stored in SO, can't we just have s SerializedField with a reference to this SO?

**Comment by litefeel** [comment]
Hi.

- SO is pure data
- SerializedField must be on GameObject

Now. There are many things in the world.
Load some thing based on the camera's field of view.
So I need to create GameObject from the data.
